# Generated by Django 2.1.15 on 2020-07-04 04:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_user_user_intro'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='follewers',
            new_name='followers',
        ),
    ]
